stages:
  - publish

build-image:
  image: docker:latest
  before_script: ['docker info']
  services: ['docker:dind']
  stage: publish
  script:
    - chmod +x ./build.sh
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest
  only: [tags, master]
  tags: [docker]
